### PR TITLE
refactor($package): lock manifest and add release script

### PR DESCRIPTION
**Pull request by ghost**
adds native npm lock functionality and creates a script which will affords automatic CHANGELOG
updates by following some smiple conventions. recommended for use with commitizen/cz-cli.

---
This change is [Reviewable](https://reviewable.io/reviews/mattstratton/language-hugo/11)

### CODE REVIEW

**Comment by ghost** [comment]
I'm not signing anything.

**Comment by jhabdas** [comment]
@dco suck it robot

**Comment by ghost** [comment]
@mattstratton for context I noticed you released `0.4.0`. The release notes don't show anything and the CHANGELOG has ostensibly not been updated since `0.1.0`.

As a result, please enjoy this pull which adds an npm lock file to your repo (recommended by NPM) and also a dev dependency called `standard-version` which is simple and helps keep your GH in synch with your NPM and updates your changelog with the deets with about two lines of scripting and some simple commit conventions.

For commit conventions see: https://github.com/commitizen/cz-cli
To release the project simple do `npm i && npm run release`
[Standard Version docs](https://github.com/conventional-changelog/standard-version) you will find is easy to use to keep changelogs updated.

Regarding @dco, I despise automation of this sort and I'm not signing-off on anything. This is open source development. We build together or projects suffer and lawyers win. As I mentioned above, I will not sign off on anything, and that's precisely the reason I stopped contributing to Hugo itself.

**Comment by mattstratton** [comment]
I’m tempted to just close this PR as i don’t need the change enough to warrant the disrespectful tone in your very first communication. 

I believe in collaborative development. You have an ax to grind about DCO, obviously, but you don’t take a second to find out why it’s enabled on this repo. You start right into lecturing me. 

In fact, i am going to close this PR. Please come back when you’d like to collaborate and not lecture.

**Pull request closed without merging**
